language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"  == "dhis2/core-resource-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn clean deploy --settings deploy/settings.xml && exit 0;
  fi
env:
  global:
  - secure: oCdg8zL8wZIgK2sHDc7rfRCjMp/5enVzCGZtqgt+4fCB3uDM3nwOjV8y9E983tXVpo6kc+hzi/GzhZD1DsvX+Zkc4x/pV1yYHxfLqkHuXG/xzJhpuhhZK2OIypnEO0tvgYw5ybTMwnWwu89giS//Syv8ESa7ATwCE0vGD8INIFZTsW1o7HF/gCf+nlSTYebPTVJGLasyfOT8saRLO0v7k80XaIZP5tjxghLKfdm8rPeQA26JZQxSVjOAMKi1zcBq3S1FPqMLDqMiI+3umHf8YDRyJ3ObNDZXlg9dAe3aInX2fEfSpkekLcgI7vHkjXR48Buo8uKbJXLKfEykz0WOIL8e5SxtAijEfazaC5nlyN848Bwfp4Uj6qRrTu/TfmfJf4fOPCvAvEYGu/9oyDmeTC2n2+YWurJUG62jAoH6mOkNtJZZl4qeLe/0Zs7WyGdnHzdeRGIB5VQ2uSjqqEQzGhoqMwaix0D8pln1okBk49GWq322kzyB+gj0QqnKNJxSk8U+JuNqNjFFhGGXVhPfWRkcKVOkfGNr8+svPQ/GLRrKLeOAabDswhCBf6ElspBFp7PrGaUzYAdWAs8ROeZ3eXi43T4BkoDbGIBIIEEeQpnVpXg/MsZT4AxStxdV8mhkfh2UVQi4kBPQjzq46svtnlkBzWrgg89FjrHcqG+pL0o=
  - secure: Ul7M38pFgaA3JH47xotvXQ70apPWyB58fXcJyboAkosdhp844ZICZzdAEkcbjRSFyWyKOwMKRmpPRhQlK+PN5nzjhNwvAKSvpImFH/AB4PNd78gLgoL66KcjkILObp/FMJ5ex9qOsxWYHT9MbP+JJa2cmGQ/vunZyr8iuoePXTgQWCv4HQ4hvDdGuuHJajQkg1Cc4AFED4uQk5acWZozKmFS1TB0NcAvO2IBzUv3fomv3MYNe27NLN2Zt+Gou45rDa0f8RyJYhaQ4uVrie7Wwk70oT8TzpJxLNqSYti9bsmk2pKLzf1KG6IT/Bd43BYJB43j8dqQ9ENd+yNrkxz6Uk19HykwztxmHIXCkeLTyYlphDe/iA/GR+f18NBjDK0SEFLqRieweLr1osj4HvNA2Xf99LeDMa4QWvY4HqFbS4l/2i1poBX3i5jZ7H7t7zxbQkLHZkos4baNzDM4fdjmUr1LXTQV0beGeHrYhKX3fnOjqD0hQpt0AgvfS7vW4bmIpQrNPyuUFawRYZ8huuK9v7dqmHH6lGvKj5WEZzIx7ePitGp+sRYxXwAe6+IfI3RZMpHDvMxP/XJzHHvISGim8ZsYJXxYOIexvpKqsXjS2A2iIS+DKxbvn8yG9ChDjCfmt0DHraAwDEGznD/wWd9ch0Gr1Was/vJ+GINjXSCKbiw=
