language: node_js
node_js:
- '8'
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run build
deploy:
- provider: script
  script: deploy-build
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: zJi38u+OcALaNi7U5gVLDAz3HkND9pAI9aKLcUHXByh1me+vDxFJNXCyejdZWfOB2r97Y5AbC6st5T8SAsgHRQ731xGbYquBjwoBSl81VHxGE9WXe4mb5KEWv7+WPBjHcQzYs2Hv9YVlgpn8rzztL9w8evuQMedokKxiC9y/tVheG5bM7pJF6XC4W5VpFP3cUtBfa7oTMhCDObJezNHfuqzvV8i9SjDMI6OY4QBeQM/gUbyMO78NTK6JRD+GpnFCCbOco9ZdF0/1tDIh442w+o35+gCqDx3JjVbjwr9Sm7/Nu7wbXx9wjQNCBPfaOMync3uPZImCBI3FUp7oJ05fVCKr4jIdcmvvGNGJSDey7eSIQDIBFUZJSsdenjBYuuTMy31SwIzYpLZaIGDxrZvs/KYD25+s5e2LsFwdW/eO6b7ZFgzfhSBLWE8gkZsHBkXQVxqQQEeabvHMKdCOMGrs6sWzZAjkEZkGoL5ac5klTRmQqH2VE72uWNjJbBeH3HAlgSBdzm+T0Xedl5sJubI/q0BXoXlJf4eb/hRAUO8XKtArDjWb9p54e8/8dQwt7ta6qVfDJIg74Hb9AIoi5omVo19HojNfqQ2CSQ2WuZNTlxGojpNh8SqUxLXHxARBBeZuboCyaP1GDFlqH00EplDclVPj6iKB71OzlkMYmVX0zfQ=
  - secure: jBaxCMOXmWYlJYQrgpFEQwR77NqBsRD0y946rFsZ/sQquw5+ckC/Dv6LmSHNq+0+eXgKsDQXzLsDpKy8hsOIZpWHeH3kHeKKPFrd2/EGd4PNPgJJ/ZGQRxDYj0CKb9b/C6TlEBfNGX5UDjOq21OjjLBRYBG3L71ag3U+obZxODbYHyOrEOvYDRlp4wRWz2qV9yqyMFk/KEVjMPF8q6y1LunoHP9IreDR1BQU16Z/KHqp9YoI/x21OAHVqKsq8920UQfOF4QhK15uLNON61BuOU9haC/1YppO0oUa5dgrbjjV/fHUF2yX1+WvBQ5eSSKRAMlvlX3SaQmTjdw+rq41AsowDtEbZ7UrTnK/GS9GjzGZL1Le1Sn5jLJVSLXXnAJkqgiC7RpKUZsVoNHi5e7DWCOjUiLPmMR8nllCHEyhOwYLWCBOHATYqdbFRzDgXO+vI0s6ZRYry1x0k4yBj6h4dx4uLtoLaZsVJ/oax4rdHFwQItM0qptXVHjYh6yPY3XGNSz/4gH30pdQ5gjoxlryOVVudrBJXNtNIJ/S/f5zIi1hrHZweW1H+XJA6TQ4oQ2lBBhTgiRaZb1pn6Y/SwapPWfrOOs/M1fYNPv31T/A3R3H2p6I2fdG3A5LPx84J+eAgONhafM/uG6hJn7jka6V1qDi6YnjJlvrCskykHh52og=
