sudo: false
language: node_js
node_js:
  - 6.1.0
script:

script:
  - "cd react-14 && npm install && cd .."
  - "cd react-15 && npm install && cd .."
  - "cd lodash-fp && npm install && cd .."
  - "npm run build"
